In [1]:
import os

In [2]:
import torch
import torchvision
torch.cuda.is_available()
import torch
print(torch.__version__)
print(torch.version.cuda)


2.1.0+cu118
11.8


In [3]:
import glob

In [4]:
from IPython.display import Image,display

In [5]:
!nvidia-smi

Tue Nov 21 02:26:46 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [6]:
HOME = os.getcwd();

In [7]:
print(HOME)

/content


In [8]:
!pip install ultralytics==8.0.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 219.8/219.8 kB 4.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 6.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.6/190.6 kB 7.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 9.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 7.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 7.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 12.9 MB/s eta 0:00:00
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144555 sha256=4b3ea138cd9c5a767151fd77d3e2b08b421bf5e8d839c921779da14a8c239606
  Stored in directory: /root/.cache/pip/wheels/12/93/dd/1f6a127edc45659556564c5730f6d4e300888f4bca2d4c5a88
Successfully built antlr4-python3-runtime


In [9]:
import ultralytics

In [10]:
ultralytics.checks()

Ultralytics YOLOv8.0.0 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 26.9/78.2 GB disk)


In [11]:
!mkdir {HOME}/datasets

In [12]:
%cd {HOME}/datasets

/content/datasets


In [13]:
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="jgvGiRkZaIuu8ohhl4r0")
project = rf.workspace("project-sign-detection").project("traffic-sign-cdfml")
dataset = project.version(2).download("yolov5")


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.3/63.3 kB 1.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.7/178.7 kB 6.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.1/49.1 MB 19.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 kB 7.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.2/72.2 kB 10.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 8.4 MB/s eta 0:00:00
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.1.1
    Uninstalling pyparsing-3.1.1:
      Successfully uninstalled pyparsing-3.1.1
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.8.1.78
    Uninstalling opencv-python-headless-4.8.1.78:
      Successfully uninstalled opencv-python-headless-4.8.1.78
  Attempting uninstall: idna
    Found existing

loading Roboflow workspace...
loading Roboflow project...



Extracting Dataset Version Zip to Traffic-Sign-2 in yolov5pytorch:: 100%|██████████| 4198/4198 [00:00<00:00, 10098.95it/s]


In [14]:
%cd {HOME}

/content


In [16]:
from ultralytics import YOLO
model = YOLO("yolov8s.pt")
model.train(data=f'{dataset.location}/data.yaml',epochs=100,imgsz=640)

yolo/engine/trainer: task=detect, mode=train, model=yolov8s.yaml, data=/content/datasets/Traffic-Sign-2/data.yaml, epochs=100, patience=50, batch=16, imgsz=640, save=True, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=True, dnn=False, plots=False, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, war

In [36]:

!YOLO task=detect mode=val model=f{home}/runs/detect/train2/weight/best.pt data={dataset.location}/data.yml

SyntaxError: ignored

In [24]:

model.val(model=f'{HOME}/runs/detect/train2/weight/best.pt',data=f'{dataset.location}/data.yaml')

Ultralytics YOLOv8.0.0 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Fusing layers... 
Model summary: 168 layers, 11133711 parameters, 20607 gradients
val: Scanning /content/datasets/Traffic-Sign-2/valid/labels.cache... 488 images, 0 backgrounds, 0 corrupt: 100%|██████████| 488/488 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 31/31 [00:06<00:00,  5.01it/s]
                   all        488        529      0.926      0.927      0.954      0.795
          do_not_enter        488         30          1      0.949      0.991      0.902
           do_not_stop        488         30      0.803      0.953      0.953      0.873
         do_not_turn_l        488         34      0.989          1      0.995      0.905
         do_not_turn_r        488         31      0.792      0.935      0.963      0.894
         do_not_u_turn        488         30      0.945        0.9      0.968      0.833
       ente

In [41]:

!yolo task=detect mode=predict model=/runs/detect/train/weight/best.pt conf=0.25 source='parkingsign.mp4'

NotImplementedError: ignored

In [44]:
%cd {HOME}
model.predict(model=f'{HOME}/runs/detect/train2/weight/best.pt',conf=0.25,source='parkingsign.mp4',save=True)

Ultralytics YOLOv8.0.0 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Fusing layers... 
Model summary: 168 layers, 11133711 parameters, 20607 gradients


/content


video 1/1 (1/154) /content/parkingsign.mp4: 640x384 1 u_turn, 24.1ms
video 1/1 (2/154) /content/parkingsign.mp4: 640x384 1 parking, 1 u_turn, 16.3ms
video 1/1 (3/154) /content/parkingsign.mp4: 640x384 1 parking, 1 u_turn, 15.4ms
video 1/1 (4/154) /content/parkingsign.mp4: 640x384 1 parking, 1 u_turn, 8.6ms
video 1/1 (5/154) /content/parkingsign.mp4: 640x384 1 parking, 1 u_turn, 14.0ms
video 1/1 (6/154) /content/parkingsign.mp4: 640x384 1 parking, 1 u_turn, 9.2ms
video 1/1 (7/154) /content/parkingsign.mp4: 640x384 1 parking, 1 u_turn, 8.2ms
video 1/1 (8/154) /content/parkingsign.mp4: 640x384 1 parking, 1 u_turn, 8.6ms
video 1/1 (9/154) /content/parkingsign.mp4: 640x384 1 u_turn, 9.2ms
video 1/1 (10/154) /content/parkingsign.mp4: 640x384 1 u_turn, 8.5ms
video 1/1 (11/154) /content/parkingsign.mp4: 640x384 1 u_turn, 11.0ms
video 1/1 (12/154) /content/parkingsign.mp4: 640x384 8.5ms
video 1/1 (13/154) /content/parkingsign.mp4: 640x384 1 left_right_lane, 1 u_turn, 9.3ms
video 1/1 (14/154) /c

[tensor([[5.50000e+02, 1.01000e+02, 6.52000e+02, 3.32000e+02, 3.94287e-01, 1.80000e+01]], device='cuda:0'),
 tensor([[5.50000e+02, 1.00000e+02, 6.52000e+02, 3.31000e+02, 3.39844e-01, 1.80000e+01],
         [5.50000e+02, 1.02000e+02, 6.50000e+02, 3.32000e+02, 2.95898e-01, 1.00000e+01]], device='cuda:0'),
 tensor([[5.49000e+02, 9.90000e+01, 6.53000e+02, 3.31000e+02, 3.50342e-01, 1.80000e+01],
         [5.50000e+02, 1.01000e+02, 6.51000e+02, 3.32000e+02, 2.91016e-01, 1.00000e+01]], device='cuda:0'),
 tensor([[5.50000e+02, 1.01000e+02, 6.52000e+02, 3.32000e+02, 3.61084e-01, 1.00000e+01],
         [5.50000e+02, 9.90000e+01, 6.54000e+02, 3.30000e+02, 3.09082e-01, 1.80000e+01]], device='cuda:0'),
 tensor([[5.50000e+02, 1.01000e+02, 6.52000e+02, 3.32000e+02, 4.45557e-01, 1.00000e+01],
         [5.50000e+02, 1.00000e+02, 6.54000e+02, 3.30000e+02, 2.71973e-01, 1.80000e+01]], device='cuda:0'),
 tensor([[5.50000e+02, 1.01000e+02, 6.54000e+02, 3.32000e+02, 3.85010e-01, 1.00000e+01],
         [5.490

In [50]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [49]:
from google.colab import files
files.download('runs/detect/predict/parkingsign.mp4')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>